### ISSUE TITLE
Output package homepage for fast changelog access

### ISSUE THREAD

**Issue by jgierer12** [silverwind/updates#10]
Often, I want to look at the changelog before updating a package. It would be cool if `updates` could output the `homepage` specified in the package's `package.json` to get to the changelog faster:

```console
$ updates
NAME        OLD       NEW       HOMEPAGE
chalk       1.3.0     2.3.0     https://github.com/chalk/chalk#readme
got         ^7.0.1    ^8.0.1    https://github.com/sindresorhus/got#readme
minimist    ^1.0.0    ^1.2.0    https://github.com/substack/minimist
```

**Comment by silverwind** [comment]
Yes, this seems like a good idea. I often have to check for changelogs while updating.

**Comment by silverwind** [comment]
One concern, thought: While updating dependencies, I'm primarily interested in changelogs or if those do not exist, the commit history. Often, the homepage does not offer the information, but a link to the repository would.

Now this is a bit tricky because the `repository` field in package.json is usually a git:// url, but I guess with a bit work, we could make it work for public hosting services like GitHub, GitLab or Bitbucket. Ideally, a direct link to the commit history would be nice.

**Comment by jgierer12** [comment]
That is a valid concern. We can get the repo URL from the `repository` field with [`hosted-git-info`](https://www.npmjs.com/package/hosted-git-info). Since some packages don't specify a `repository` field, I think we should still fall back to `homepage` though.

If you're OK with adding an extra dep (`hosted-git-info`), I will implement it like this in my PR.
